{
  "hash": "713e45c2115c410a467d59a58a876a49",
  "result": {
    "markdown": "---\ntitle: \"Basic Statistical Concepts in R\"\npagetitle: \"{{< meta title >}}\"\nsubtitle: \"Overview of Descriptive Measures, Hypothesis Testing & Visualization\"\nauthor: \"Bilal Mustafa\"    \ndate: \"2024-08-14\"     \n#slug: \"basic-statistical-concepts-in-r\"\ndescription: >\n  An introductory guide to fundamental statistical concepts in R.\n  Learn how to compute descriptive measures, conduct t-tests,\n  construct confidence intervals, and create informative visualizations\n  with practical R code examples.\ncategories: [Statistics, R Programming, Data Analysis, Descriptive Statistics]\ntags: [Descriptive Statistics, Hypothesis Testing, T-Test, Confidence Intervals, Data Visualization, Beginners Guide, Quantitative Analysis, Statistical Methods]\nimage: \"image.jpg\"\nimage-alt: \"Graphical illustration of basic statistical concepts in R\"\n\ntwitter-card:\n  title: \"Core Statistical Concepts in R\"\n  description: >\n    A hands-on tutorial to learn descriptive statistics, t-tests,\n    confidence intervals, and visualization techniques in R.\n  image: \"image.jpg\"\n  image-alt: \"Twitter thumbnail for basic statistics tutorial\"\n\nopen-graph:\n  title: \"Basic Statistical Concepts in R | Bioinfo Guide Book\"\n  description: >\n    Explore essential statistical methods in R—descriptives, hypothesis testing,\n    and plotting—through clear examples and code.\n  image: \"image.jpg\"\n  image-alt: \"Open Graph image for basic statistics guide\"\n\nformat:\n  html:\n    code-link: true\n    df-print: paged\n    code-copy: true\n---\n\n\n# Introduction:\n\nStatistics are a very important part of data analysis because they turn raw data into ideas that can be used.\nStatistical tools can help you make smart choices whether you're summarizing data, seeing patterns, or testing theories.\nThis guide teaches you basic statistical ideas using R.\nIt focuses on t-tests, data visualization, and descriptive statistics, all while using a single dataset.\n\n------------------------------------------------------------------------\n\n# Dataset: mtcars\n\nWe will use the mtcars dataset that comes with R for this guide.\nThere are factors like miles per gallon (mpg), number of cylinders, horsepower, and weight for 32 different car models in this dataset.\nThis dataset is great for learning about basic statistical ideas and trying hypotheses.\n\nFirst, let's quickly look at the dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load and view the mtcars dataset\ndata(\"mtcars\")\nhead(mtcars)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"mpg\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"cyl\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"disp\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"hp\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"drat\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"wt\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"qsec\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"vs\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"am\"],\"name\":[9],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gear\"],\"name\":[10],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"carb\"],\"name\":[11],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"21.0\",\"2\":\"6\",\"3\":\"160\",\"4\":\"110\",\"5\":\"3.90\",\"6\":\"2.620\",\"7\":\"16.46\",\"8\":\"0\",\"9\":\"1\",\"10\":\"4\",\"11\":\"4\",\"_rn_\":\"Mazda RX4\"},{\"1\":\"21.0\",\"2\":\"6\",\"3\":\"160\",\"4\":\"110\",\"5\":\"3.90\",\"6\":\"2.875\",\"7\":\"17.02\",\"8\":\"0\",\"9\":\"1\",\"10\":\"4\",\"11\":\"4\",\"_rn_\":\"Mazda RX4 Wag\"},{\"1\":\"22.8\",\"2\":\"4\",\"3\":\"108\",\"4\":\"93\",\"5\":\"3.85\",\"6\":\"2.320\",\"7\":\"18.61\",\"8\":\"1\",\"9\":\"1\",\"10\":\"4\",\"11\":\"1\",\"_rn_\":\"Datsun 710\"},{\"1\":\"21.4\",\"2\":\"6\",\"3\":\"258\",\"4\":\"110\",\"5\":\"3.08\",\"6\":\"3.215\",\"7\":\"19.44\",\"8\":\"1\",\"9\":\"0\",\"10\":\"3\",\"11\":\"1\",\"_rn_\":\"Hornet 4 Drive\"},{\"1\":\"18.7\",\"2\":\"8\",\"3\":\"360\",\"4\":\"175\",\"5\":\"3.15\",\"6\":\"3.440\",\"7\":\"17.02\",\"8\":\"0\",\"9\":\"0\",\"10\":\"3\",\"11\":\"2\",\"_rn_\":\"Hornet Sportabout\"},{\"1\":\"18.1\",\"2\":\"6\",\"3\":\"225\",\"4\":\"105\",\"5\":\"2.76\",\"6\":\"3.460\",\"7\":\"20.22\",\"8\":\"1\",\"9\":\"0\",\"10\":\"3\",\"11\":\"1\",\"_rn_\":\"Valiant\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Getting to Know the Data\n\nIt's important to understand the material we're working with before we start the analysis.\nThe following factors are in the mtcars dataset:\n\n-   mpg: Miles per gallon\n-   cyl: Number of cylinders\n-   hp: Horsepower\n-   wt: Weight (1000 lbs)\n-   am: Transmission (0 = automatic, 1 = manual)\n\n------------------------------------------------------------------------\n\n# Descriptive Statistics\n\nDescriptive statistics give an overview of the shape, central trend, and dispersion of a dataset's distribution.\nLet's figure out some important numbers that describe mpg, hp, and wt.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate descriptive statistics\nsummary(mtcars[, c(\"mpg\", \"hp\", \"wt\")])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      mpg              hp              wt       \n Min.   :10.40   Min.   : 52.0   Min.   :1.513  \n 1st Qu.:15.43   1st Qu.: 96.5   1st Qu.:2.581  \n Median :19.20   Median :123.0   Median :3.325  \n Mean   :20.09   Mean   :146.7   Mean   :3.217  \n 3rd Qu.:22.80   3rd Qu.:180.0   3rd Qu.:3.610  \n Max.   :33.90   Max.   :335.0   Max.   :5.424  \n```\n:::\n:::\n\n\nAs you can see, this summary shows the mean, median, minimum, maximum, and quartiles for each measure.\nThat is, the cars in this group get about 20.09 miles per gallon on average, with a range of 10.4 to 33.9.\n\n------------------------------------------------------------------------\n\n# Data Visualization\n\nVisualizing data is an important part of figuring out how it is spread out and how different factors are related.\nTo look into the mtcars collection, we'll make a number of plots.\n\n1.  Histogram of mpg A histogram shows how a single numerical value is spread out.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of miles per gallon (mpg)\nhist(mtcars$mpg, main = \"Distribution of Miles Per Gallon (mpg)\", xlab = \"Miles Per Gallon\", col = \"lightblue\")\n```\n\n::: {.cell-output-display}\n![](t_test_files/figure-html/unnamed-chunk-3-1.png){fig-alt='Histogram of miles per gallon (mpg)' width=672}\n:::\n:::\n\n\n2.  Boxplot of mpg by Transmission You can compare distributions between groups with a boxplot. We will now compare the mpg of cars with automatic and manual engines.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Boxplot of mpg by transmission type\nboxplot(mpg ~ am, data = mtcars, main = \"MPG by Transmission Type\", xlab = \"Transmission (0 = Automatic, 1 = Manual)\", ylab = \"Miles Per Gallon\", col = c(\"orange\", \"lightgreen\"))\n```\n\n::: {.cell-output-display}\n![](t_test_files/figure-html/unnamed-chunk-4-1.png){fig-alt='Boxplot of mpg by transmission type' width=672}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n# Comparing Means with T-Tests\n\nYou can compare the means of different groups very well with T-tests.\nOne-Sample, Independent Two-Sample, and Paired t-tests are the three main types of t-tests.\nLet's use the mtcars dataset to look into each type.\n\n------------------------------------------------------------------------\n\n## One-Sample T-Test\n\nOne-Sample T-Test checks if the mean of a single sample is the same as a number that is already known.\nWe might want to see if the mtcars dataset's average miles per gallon (mpg) is significantly different from 20 mpg.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# One-sample t-test\nt_test_one_sample <- t.test(mtcars$mpg, mu = 20)\nprint(t_test_one_sample)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tOne Sample t-test\n\ndata:  mtcars$mpg\nt = 0.08506, df = 31, p-value = 0.9328\nalternative hypothesis: true mean is not equal to 20\n95 percent confidence interval:\n 17.91768 22.26357\nsample estimates:\nmean of x \n 20.09062 \n```\n:::\n:::\n\n\nThe main idea (H₀) here is that the average mpg is 20.\nIf the p-value is less than the level of significance, which is usually 0.05, we disagree with the null hypothesis.\n\n## Independent Two-Sample T-Test\n\nWhen you use the Independent Two-Sample T-Test, you compare the means of two separate groups.\nLet's look at how many miles per gallon cars with automatic (am = 0) and manual (am = 1) engines get.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Independent Two-Sample T-Test\nt_test_independent <- t.test(mpg ~ am, data = mtcars)\nprint(t_test_independent)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  mpg by am\nt = -3.7671, df = 18.332, p-value = 0.001374\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -11.280194  -3.209684\nsample estimates:\nmean in group 0 mean in group 1 \n       17.14737        24.39231 \n```\n:::\n:::\n\n\nWhat does H₀ mean?\nIt means that there is no change in the average mpg between the two types of transmission.\nThere is a difference between the groups if the p-value is significant.\n\n## Paired T-Test\n\nThe Paired T-Test looks at how the means of the same group of people changed over time.\nEven though mtcars doesn't have a built-in matched structure, let's say we want to compare the mpg of two identical cars before and after a change.\nWe don't have this data, so let's make it up to show what we mean.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simulating mpg before and after modification\nset.seed(123)\nmpg_before <- mtcars$mpg\nmpg_after <- mpg_before + rnorm(length(mpg_before), 0, 2)  # Adding small random noise\n\n# Paired t-test\nt_test_paired <- t.test(mpg_before, mpg_after, paired = TRUE)\nprint(t_test_paired)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  mpg_before and mpg_after\nt = 0.23758, df = 31, p-value = 0.8138\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -0.6075656  0.7677806\nsample estimates:\nmean difference \n      0.0801075 \n```\n:::\n:::\n\n\nThere is no difference in mpg before and after the change, which is the null hypothesis (H₀).\nIf the p-value is significant, it means that the change made a meaningful difference.\n\n------------------------------------------------------------------------\n\n# Conclusion\n\nUsing the mtcars dataset, this guide has shown you how to use basic statistical ideas in R.\nWe began with summary statistics, made a graph of the data, and used different t-tests to compare means.\nThese tools give you a solid base for looking at data and coming to useful conclusions.\nAs you learn more advanced statistical methods, keep in mind that these basic skills will still help you a lot as you go through your data analysis experience.\n\n------------------------------------------------------------------------\n\n# Resources & References:\n\n1.  **\"R for Data Science\"** by Garrett Grolemund and Hadley Wickham\n\n    The book is available for free online.\n    [Link to the book](https://r4ds.hadley.nz/)\n\n2.  **\"An Introduction to Statistical Learning\"** by Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani\n\n3.  **\"R Documentation - t.test Function\"**\\\n\nIt's a great resource for understanding how to perform various t-tests in R.\n[Link to the documentation](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/t.test)\n\n------------------------------------------------------------------------\n",
    "supporting": [
      "t_test_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}